import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Residencial Horizon',
    slug: 'residencial-horizon',
    city: 'São Paulo',
    neighborhood: 'Jardins',
    status: 'Lançamento',
    image: 'https://picsum.photos/id/122/1200/800',
    gallery: [
      'https://picsum.photos/id/122/1200/800',
      'https://picsum.photos/id/129/1200/800',
      'https://picsum.photos/id/128/1200/800',
    ],
    description: 'Um marco de sofisticação nos Jardins. O Residencial Horizon redefiniu o conceito de viver bem, integrando natureza e arquitetura contemporânea.',
    details: {
      dorms: '3 e 4',
      area: '150 a 220 m²',
      suites: '3',
      parking: '3 Vagas',
    },
    features: ['Piscina com Borda Infinita', 'Academia High-Tech', 'Spa', 'Heliponto'],
    lat: -23.561684,
    lng: -46.655981,
  },
  {
    id: '2',
    title: 'Grand Palazzo',
    slug: 'grand-palazzo',
    city: 'Curitiba',
    neighborhood: 'Batel',
    status: 'Em Obras',
    image: 'https://picsum.photos/id/192/1200/800',
    gallery: [
      'https://picsum.photos/id/192/1200/800',
      'https://picsum.photos/id/201/1200/800',
      'https://picsum.photos/id/188/1200/800',
    ],
    description: 'Inspirado na arquitetura neoclássica, o Grand Palazzo oferece a exclusividade que você merece no coração do Batel.',
    details: {
      dorms: '4',
      area: '280 m²',
      suites: '4',
      parking: '4 Vagas',
    },
    features: ['Salão de Festas Imperial', 'Adega Climatizada', 'Cinema Privativo', 'Porte-Cochère'],
    lat: -25.443150,
    lng: -49.288696,
  },
  {
    id: '3',
    title: 'Lumina Tower',
    slug: 'lumina-tower',
    city: 'Balneário Camboriú',
    neighborhood: 'Barra Sul',
    status: 'Entregue',
    image: 'https://picsum.photos/id/235/1200/800',
    gallery: [
      'https://picsum.photos/id/235/1200/800',
      'https://picsum.photos/id/238/1200/800',
      'https://picsum.photos/id/239/1200/800',
    ],
    description: 'A luz do sol e a brisa do mar em perfeita harmonia. O Lumina Tower é o refúgio perfeito de frente para o mar.',
    details: {
      dorms: '3',
      area: '120 a 180 m²',
      suites: '3',
      parking: '2 Vagas',
    },
    features: ['Beach Club', 'Rooftop Lounge', 'Piscina Aquecida', 'Automação Residencial'],
    lat: -26.992486,
    lng: -48.633520,
  },
  {
    id: '4',
    title: 'Eco Vibe',
    slug: 'eco-vibe',
    city: 'São Paulo',
    neighborhood: 'Vila Madalena',
    status: 'Lançamento',
    image: 'https://picsum.photos/id/69/1200/800',
    gallery: [
      'https://picsum.photos/id/69/1200/800',
      'https://picsum.photos/id/70/1200/800',
    ],
    description: 'Sustentabilidade e design moderno se encontram na Vila Madalena. Certificação LEED e materiais naturais.',
    details: {
      dorms: '2 e 3',
      area: '80 a 110 m²',
      suites: '2',
      parking: '2 Vagas',
    },
    features: ['Horta Comunitária', 'Energia Solar', 'Carregador Carro Elétrico', 'Bike Sharing'],
    lat: -23.553200,
    lng: -46.688900,
  },
];

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Empreendimentos', path: '/empreendimentos' },
  { label: 'A Aura', path: '/#sobre' },
  { label: 'Contato', path: '/#contato' },
];
